eng_txt = ["language", 
           "reference", 
           "The path to the KOMPAS file :", 
           "Specify the KOMPAC assembly file", 
           "The path to the specification .xl :", 
           "Specify the path to the table with the specification", 
           "Conversion to Specification", 
           "Auto positioning", 
           "Detail type", 
           "Name", 
           "Quantity and pcs.", 
           "Is included to",
           "Material and thickness"]


ru_txt = ["Язык",
          "Справка",
          "Путь к файлу KOMPAC :",
          "Указать сборочный файл KOMPAC",
          "Путь к спецификаци .xl :",
          "Указать путь к таблице со спецификацией",
          "Конвертация в спецификацию",
          "Авторасстановка позиций",
          "Вид ДСЕ",
          "Наименование",
          "Количество и ед.",
          "Куда входит",
          "Материал и толщина"]
