eng_txt = ["language", 
           "FAQ", 
           "The path to the KOMPAS file :", 
           "Specify the KOMPAC assembly file", 
           "The path to the specification .xl :", 
           "Specify the path to the table \n with the specification", 
           "Conversion to Specification", 
           "Auto positioning", 
           "Detail type", 
           "Name", 
           "Quantity and pcs.", 
           "Is included to",
           "Material and thickness",
           "Covering",
           "Comment",
           "Select/Cancel all",
           "Enter the primary application \n or leave it empty"]

ru_txt = ["language",
          "FAQ",
          "Путь к файлу KOMПAC :",
          "Указать сборочный файл KOMПAC",
          "Путь к спецификаци .xl :",
          "Указать путь к таблице Exсel",
          "Конвертация в спецификацию",
          "Авто. позиция",
          "Вид ДСЕ",
          "Наименование",
          "Количество и ед.",
          "Куда входит",
          "Материал и толщина",
          "Гальваника/покраска",
          "Примечание",
          "Выбрать/отменить всё",
          "Вписать первичное применение \n или оставить пустым"]

FAQ_txt_ru = ["Программа открывает сборки формата KOMПAC и переводит выбранные пользователем параметры спецификации в таблицу формата .xls \n \n - для работы наобходим KOMPAC \n \n - программа не поддерживает устарешие таблицы формата .xl \n \n - для выбора параметров спецфикации можно щелкать на текст, а не только на окно для галочки \n \n - почта для вопросов - dinner.real@gmail.com"]
FAQ_txt_eng = ["The program opens KOMPAS format assemblies and translates the specification parameters selected by the user into a format table .xls\n\n To work, we need KOMPAC \n \n The program does not support the installation of a format table.xl \n \n To select the specialification parameters, you can click on the text, and not just on the window for the check mark \n\n Mail for questions - dinner.real@gmail.com"]