eng_txt = ["language", 
           "reference", 
           "The path to the KOMPAS file :", 
           "Specify the KOMPAC assembly file", 
           "The path to the specification .xl :", 
           "Specify the path to the table with the specification", 
           "Conversion to Specification", 
           "Type of DSE", 
           "Name", 
           "Quantity", 
           "Thickness", 
           "Material", 
           "Where it includes"]


ru_txt = ["Язык",
          "Справка",
          "Путь к файлу KOMPAC :",
          "Указать сборочный файл KOMPAC",
          "Путь к спецификаци .xl :",
          "Указать путь к таблице со спецификацией",
          "Конвертация в спецификацию",
          "Вид ДСЕ",
          "Наименование",
          "Количество",
          "Толщина",
          "Материал (вид)",
          "Куда входит"]
